### ISSUE TITLE
After 5 times of reflashing I finally need help pls

### ISSUE THREAD

**Issue by thefallenarchangel** [V0r-T3x/Fancytools#1]
Hey, 

first of all thanks for the work, i really appreciate the work that goes in to this projects.

Aluminum Ice 1.8.5 - latest
Raspberry Pi Zero 2 w
SanDisk Extreme 64gb 

I really want to have a pwnachu, but I tried 5 times of reflashing the image and following every step, made sure I have internet connection and everything like described. I did alot of stuff this year with pwna and am really not a noob and understand the fundamentals. 

After following every step precisely, everything works fine until the last step after installing it just does not starts the Web UI but I can still ssh in and everything is fine but pwny is dead.
 
This is my Error:

pi@pikachu:~ $ sudo pwnagotchi-launcher
0
1
0
1
0
1
0
[2024-08-31 19:30:03,495] [INFO] webcfg: Plugin loaded.
[2024-08-31 19:30:03,496] [INFO] Session-stats plugin loaded.
[2024-08-31 19:30:03,499] [INFO] [update] plugin loaded.
[2024-08-31 19:30:03,500] [INFO] grid plugin loaded.
[2024-08-31 19:30:03,502] [INFO] [led] plugin loaded for /sys/class/leds/led0/brightness
[2024-08-31 19:30:03,505] [INFO] 
[2024-08-31 19:30:03,512] [INFO] [FANCYTOOLS] Beginning Fancytools load
[2024-08-31 19:30:03,513] [INFO] [FANCYTOOLS]====================
ln: failed to create symbolic link '/usr/local/bin/fancytools': File exists
[2024-08-31 19:30:03,567] [INFO] BT-TETHER: Successfully loaded ...
[2024-08-31 19:30:03,628] [INFO] [FANCYTOOLS] Default tools
[2024-08-31 19:30:03,630] [INFO] [FANCYTOOLS]====================
[2024-08-31 19:30:03,631] [INFO] [FANCYTOOLS] dev tool
[2024-08-31 19:30:03,632] [INFO] [FANCYTOOLS] tool don't need install
[2024-08-31 19:30:03,633] [INFO] [FANCYTOOLS]====================
[2024-08-31 19:30:03,634] [INFO] [FANCYTOOLS] terminal tool
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 154, in <module>
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/display.py", line 12, in __init__
    super(Display, self).__init__(config, hw.display_for(config), state)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/view.py", line 51, in __init__
    th = pwnagotchi._theme['theme']['main_elements']
KeyError: 'main_elements'
[2024-08-31 19:30:03,654] [INFO] [FANCYTOOLS] tool need install
[2024-08-31 19:30:03,655] [INFO] [FANCYTOOLS]====================
[2024-08-31 19:30:03,655] [INFO] [FANCYTOOLS] fancygotchi tool
[2024-08-31 19:30:03,658] [INFO] [FANCYTOOLS] Fancygotchi is installed manually
[2024-08-31 19:30:03,659] [INFO] [FANCYTOOLS] tool don't need install
[2024-08-31 19:30:03,659] [INFO] [FANCYTOOLS]====================
[2024-08-31 19:30:03,660] [INFO] [FANCYTOOLS] Custom tools
[2024-08-31 19:30:03,660] [INFO] [FANCYTOOLS]====================
[2024-08-31 19:30:03,660] [INFO] [FANCYTOOLS] Ending Fancytools load
1
0
1
0
1
0
1
0
1
0
1
0
1

thanks for the Help!

thefallenarchangel

**Comment by V0r-T3x** [comment]
Did you download and place a theme as explained inside the readme?

**Comment by thefallenarchangel** [comment]
Yes I used the default path /usr/local/share/pwnagotchi/custom-plugins/themes/
I copied the whole themes folder and placed it there. Is this wrong? Should I just place the theme I want or is it now and Issue to have multiple themes in this folder?

I really feel dump right now, what am I missing. 

thanks for the fast answer, appreciated

**Comment by thefallenarchangel** [comment]
How should the display configuration be if i want to use waveshare display? is this correct like this? I just cut out the maybe relevant stuff of my config.toml.

main.custom_plugins = "/usr/local/share/pwnagotchi/custom-plugins/"

ui.fps = 0.0
ui.font.name = "DejaVuSansMono"
ui.font.size_offset = 0

ui.display.enabled = true
ui.display.rotation = 0
ui.display.type = "waveshare_2"
ui.display.color = "black"

main.plugins.fancytools.enabled = true

fancygotchi.theme = "pwnachu"
fancygotchi.rotation = 0

fs.memory.enabled = false
fs.memory.mounts.log.enabled = false
fs.memory.mounts.log.mount = "/var/log"
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true
fs.memory.mounts.log.rsync = true

fs.memory.mounts.data.enabled = false
fs.memory.mounts.data.mount = "/var/tmp/pwnagotchi"
fs.memory.mounts.data.size = "10M"
fs.memory.mounts.data.sync = 3600
fs.memory.mounts.data.zram = false
fs.memory.mounts.data.rsync = true

the pointed files are all there like they should be and like it is described in the ReadME.

**Comment by V0r-T3x** [comment]
The compatible theme should be there.
https://github.com/V0r-T3x/Fancygotchi_themes/tree/main/fancygotchi_1.0

the path for the themes folder should be this:
`/usr/local/share/pwnagotchi/custom-plugins/themes/pwnachu/...`

and the config file seems ok.

Honestly, I don't see where the problem can be. And this version is almost dead... I got too much problem and I was very limited.

**Comment by thefallenarchangel** [comment]
In my fist example I used the 2.0 theme. I just tried the 1.0 and this time it works fine. WOW. Thanks for pointing to the version, but i still dont get it. Thanks man keep up the good work.

**Comment by V0r-T3x** [comment]
yeah, im actually backing the v2.0, and I need to adjust some folder with new themes system.

i'm working on a better wiki for the next version. I added some additional new options, and reviewed some old one.

And the new one is less invasive, easier to install, and have a default theme hardcoded in itself to avoid some basic errors.

you can see the new options in the wiki 2.0:

https://github.com/V0r-T3x/fancygotchi/wiki/Theme-options
